export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",

  UNIVERSITY_ADMIN = "UNIVERSITY_ADMIN",

  SENATE = "SENATE",

  DEAN = "DEAN",

  HOD = "HOD",

  EXAM_OFFICER = "EXAM_OFFICER",

  LECTURER = "LECTURER",

  COURSE_ADVISER = "COURSE_ADVISER",

  STUDENT = "STUDENT",
}